# .github/workflows/ci.yml
name: CI Pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
        python-version: "3.11"
      - name: Install dependencies
        run: pip install -r Assignment5/requirements.txt
      - name: Run tests
        run: |
        cd Assignment5
        coverage run -m pytest -q
        coverage report --fail-under=90